### ISSUE TITLE
particlex主题问题

### ISSUE THREAD

**Issue by Aircraft-carrier** [zhwuyuhehe/zhwuyuhehe.github.io#3]
你好我想问你一些主题的问题，我的站建好后长成这个样子和argvchs佬的有些不同，不知道你建站的时候是否遇到类似的问题

<img width="1198" alt="image" src="https://github.com/zhwuyuhehe/zhwuyuhehe.github.io/assets/122367292/9fec48ba-58d2-4715-887f-f95f13b3479e">

**Comment by zhwuyuhehe** [comment]
我并没有遇到这种情况，一个代码块，应该是独占整行的。

- 你可以先排查一下版本兼容性(我是Hexo6.3.0)。
- 需要整合一下pandoc(我仅仅把他放到nodejs安装目录就可以使用了)。
- 在创建页面的时候，本地编译器先检查一下MD语法，预览一下是否正常。
- 完成生成页面后先排查一下本地文件是否在此环节出现问题。
- 这是我的Quick Start页面的样子。
![image](https://github.com/zhwuyuhehe/zhwuyuhehe.github.io/assets/47172382/43fa8e37-fc81-4c96-a570-ba7fd4f4c6fc)

**Comment by Aircraft-carrier** [comment]
好的谢谢我刚刚已经解决了，大概就是根目录下的yml配置没有修改
<img width="408" alt="image" src="https://github.com/zhwuyuhehe/zhwuyuhehe.github.io/assets/122367292/bce9229f-c55b-46e1-b930-f0ac2fe58a95">
